name = "consig"
version = "0.1.0"
defaultTargets = ["consig"]

[[lean_lib]]
name = "Consig"

[[lean_exe]]
name = "consig"
root = "Main"

[[require]]
name = "mathlib"
version = "git#v4.14.0"
scope = "leanprover-community"
